checkpointer:
  extra: 25
  latest: 1
  mode: epoch
criterion:
  - args:
      alpha: 0.75
    type: occupancy_focal
dataset:
  - args:
      filter_future: true
      full_sequence: true
      heatmap_time: [0, 10]
      map_normalize: 80.0
      occupancy_roi: 0.5
      occupancy_size: 256
      only_vehicles: true
      random_heatmap_count: 4
      random_heatmap_minmax: [1, 60]
      roadmap: true
      roadmap_size: 256
      signal_features: true
      use_sdc_frame: true
      waymo_eval_frame: true
    train_loader:
      args:
        batch_size: 12
        drop_last: true
      type: DALI
    type: waymo_motion
    val_loader:
      args:
        batch_size: 24
        drop_last: true
      type: DALI
logger:
  interval: 500
model:
  - args:
      decoder:
        adapter:
          args:
            conv_dim: 32
            kernel_size: 5
          type: prerefine
        num_frequency_bands: 32
        position_encoding_type: fourier
        residule_query: false
      encoder:
        adapter:
          args:
            input_mode: fpos_extra
            map_n_bands: 64
            yaw_n_bands: 64
          type: vehicle
        detach_latent: true
        input_indicies: [0, 5, 10]
        num_latent_channels: 256
        num_latents: 128
        roadgraph_ia:
          args:
            conv_1x1: 190
            in_channels: 1
            num_frequency_bands: 16
            patchify: 32
          type: image
        signal_ia:
          args:
            input_mode: fpos
            num_frequency_bands: 30
            onehot: true
          type: signal
        version: 7
    optimizer:
      args:
        lr: 0.001
        step_interval: 5
      scheduler:
        args:
          max_iter: 75
          power: 0.9
        type: poly
      type: AdamW
    type: motion-perceiver
