dataset:
  - type: sdd
    args:
      map_normalize: 30.0
      full_sequence: true
      occupancy_size: 256
      filter_future: true
      roadmap: true
      roadmap_size: 256
      heatmap_time: [0, 14]
      random_heatmap_minmax: [0, 38]
      random_heatmap_count: 3
      occupancy_roi: 0.5
      time_stride: 2
    loader:
      type: DALI
      args:
        batch_size: 8
        drop_last: true
criterion:
  - type: occupancy_focal
    args:
      alpha: 0.95
model:
  - type: motion-perceiver
    args:
      encoder:
        version: 7
        num_latents: 128
        num_latent_channels: 256
        input_indicies: [0, 5, 10]
        detach_latent: true
        adapter:
          type: vehicle
          args:
            input_mode: fpos_extra
            map_n_bands: 32
            yaw_n_bands: 8
            yaw_max_freq: 16.0
        roadgraph_ia:
          type: conv1
          args:
            raster_ch: 3
            conv_ch: 128
            num_frequency_bands: 16
            avg_pool_shape: [8, 8]
      decoder:
        position_encoding_type: fourier
        num_frequency_bands: 32
        residule_query: false
        adapter:
          type: heatmap
          args:
            num_output_channels: 128
    optimizer:
      type: AdamW
      args:
        step_interval: 5
        lr: 0.001
      scheduler:
        type: poly
        args:
          max_iter: 25
          power: 0.9
logger:
  interval: 500
