checkpointer:
  extra: 25
  latest: 1
  mode: epoch
criterion:
  - args:
      alpha: 0.75
    type: occupancy_focal
dataset:
  - args:
      filter_future: true
      full_sequence: true
      heatmap_time: [0, 10]
      map_normalize: 80.0
      occupancy_roi: 0.5
      occupancy_size: 256
      only_vehicles: true
      random_heatmap_piecewise:
        - max: 9
          min: 0
          n_random: 1
          stride: 1
        - max: 90
          min: 10
          n_random: 2
          stride: 10
      roadmap: true
      roadmap_size: 256
      signal_features: true
      time_stride: 1
      use_sdc_frame: true
      waymo_eval_frame: true
    train_loader:
      args:
        batch_size: 48
        drop_last: true
      type: DALI
    type: waymo_motion
    val_loader:
      args:
        batch_size: 96
        drop_last: true
      type: DALI
logger:
  interval: 1000
  write_tboard:
    - all
model:
  - args:
      decoder:
        adapter:
          args:
            conv_dim: 32
            kernel_size: 5
          type: prerefine
        num_frequency_bands: 32
        position_encoding_type: fourier
        residule_query: false
      encoder:
        adapter:
          args:
            input_mode: fpos_extra
            map_n_bands: 64
            yaw_n_bands: 64
          type: vehicle
        detach_latent: true
        input_indicies: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        num_latent_channels: 256
        num_latents: 128
        roadgraph_ia:
          args:
            avg_pool_shape: [8, 8]
            conv_ch: 128
            num_frequency_bands: 16
          type: conv1
        signal_ia:
          args:
            input_mode: fpos
            num_frequency_bands: 32
            onehot: true
          type: signal
        version: 8
    optimizer:
      args:
        lr: 0.001
        step_interval: 1
      scheduler:
        args:
          max_iter: 75
          power: 0.9
        type: poly
      type: AdamW
    type: motion-perceiver
