# Compose file to create tensorflow container to export waymo eval data
version: '3.3'
services:
  waymo-eval:
    shm_size: 16gb
    tty: true
    build:
      dockerfile: tf.Dockerfile
    image: mp:tf
    entrypoint:
      [
        "python3",
        "evaluate.py",
        "evaluate",
        "/ckpt/653ffb701d16be1bc0f1f1cac5e90fac",
        "--split",
        "val"
      ]
    environment:
      - PRETRAINED_ROOT=/ckpt
    volumes:
      - type: bind
        source: ./
        target: /workspace
        read_only: false
      - type: bind
        source: /path/to/checkpoints
        target: /ckpt
        read_only: false
      - type: bind
        source: /path/to/datasets
        target: /data
        read_only: false
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
